import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import BlobBackground from "@/components/BlobBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-center bg-white text-black relative min-w-screen overflow-hidden">
          <BlobBackground />
          {children}
        </main>
      </body>
    </html>
  );
}
